const avatar=document.getElementById('avatar3d'),nav=document.getElementById('nav'),intro=document.getElementById('intro'),panel=document.getElementById('panel'),orb=document.getElementById('orb'),title=document.getElementById('title'),desc=document.getElementById('desc'),chips=document.getElementById('chips'),deck=document.getElementById('deck'),count=document.getElementById('count'),status=document.getElementById('status'),modelError=document.getElementById('modelError'),bgVideo=document.getElementById('bgVideo');

const sections=[
['ai','🤖','AI + Automation','#80f7ff','Custom AI agents, GPTs, workflow automations, and research systems that save time and turn scattered work into repeatable engines.',['Custom GPTs','n8n / Make','Lead systems','AI training'],[['Ịmaya Automation Builds','Lead capture, outreach, CRM cleanup, follow-ups, and virtual assistant workflows for small teams.'],['Custom AI Assistants','Personal or business GPTs trained for a specific workflow, audience, voice, or internal knowledge base.'],['Deep Research Systems','Fast research packages with clear summaries, action plans, and reusable knowledge files.']]],
['education','🎓','Education + Workshops','#72ff9b','AI literacy and creative technology programs for students, schools, youth organizations, and working adults.',['Youth AI','Curriculum','Workshops','Creative learning'],[['Shoot With A Camera','Film, storytelling, and AI media education for youth through hands-on creation.'],['AI Club / School Programs','Prompting, short films, app ideas, responsible AI, and project-based learning.'],['Workflow Training','Practical workshops that help adults and teams use AI without getting lost in tool overload.']]],
['music','🎵','Music + Audio','#b586ff','Songs, beats, vocal coaching, mobile studio recording, sound design, and music-driven brand experiences.',['Beats','Recording','Vocal presets','Theme songs'],[['Max Starr Music','R&B, alternative rap, Afro-beats, dancehall, pop, and experimental storytelling.'],['Production Services','Custom beats, theme songs, in-the-booth coaching, and mobile recording support.'],['Audio Products','BandLab vocal presets, effect chains, visualizers, and music media packs.']]],
['visuals','🎨','Design + Film','#ff7adf','Album covers, visualizers, short videos, logos, UI icons, pitch visuals, AI art direction, and cinematic brand assets.',['Covers','Videos','Logos','Brand assets'],[['Cover + Visualizer Packs','Cover art, motion loops, promo clips, and short-form visuals for releases.'],['Brand Identity Assets','Logos, UI icons, social graphics, slide art, and stylized promo materials.'],['AI Art Direction','Prompt systems, creative concepts, and visual pipelines for campaigns or storyworlds.']]],
['engineering','🚀','Web + Engineering','#ffb84d','Websites, prototypes, interfaces, 3D concepts, no-code systems, and practical technical problem solving.',['Websites','Prototypes','3D ideas','No-code'],[['Portfolio + Brand Sites','Clean web interfaces for artists, educators, local businesses, and creative service brands.'],['Prototype Builds','Fast MVP layouts, automation demos, UI concepts, and technical proof-of-concepts.'],['Future-Tech Projects','Engineering concepts, CAD-informed ideas, robotics, bionics, aerospace, and systems design.']]],
['starrdome','🌌','StarrDome','#9f8cff','The youth creative platform vision: kids turn ideas into characters, comics, games, stories, animations, and eventually products.',['Edutainment','Game worlds','AI characters','Creator hub'],[['Idea to Franchise','A future workflow for text-to-character, comic, animation, game asset, and toy-style creation.'],['Learn · Create · Share','A safe loop where learning unlocks creation, and creation gives kids a reason to learn more.'],['StarrDome Online','A player-built world for showcasing characters, stories, and interactive creations.']]],
['products','🛒','Products + Digital Shop','#ffffff','Digital products and packaged services: presets, prompt packs, templates, AI media assets, studio kits, and creative toolkits.',['Presets','Prompt packs','Templates','Media kits'],[['Vocal Presets','Affordable preset bundles and effect chains for quick artist setup.'],['AI Media Packs','Prompt packs, visual assets, icons, covers, and reusable brand materials.'],['Studio Toolkits','Recommended home studio setups and training for creators building from scratch.']]],
['brand','🌳','StarrTree Brand','#ffd700','The umbrella identity: music, AI, education, engineering, design, services, and storyworlds rooted in one living system.',['Rooted in Light','Cosmic tree','Creative systems','Unity'],[['Central Hub','A public-facing map of the branches: what you make, teach, sell, and build.'],['Creative Services Menu','A simplified way for visitors to understand what to book or ask about.'],['Living Portfolio','A website that can keep growing without becoming slow, cluttered, or confusing.']]]
];

let sel=0;
function renderNav(){nav.innerHTML=sections.map((s,i)=>`<button class="${i===sel?'active':''}" data-i="${i}"><i>${s[1]}</i><span>${s[2]}</span></button>`).join('');nav.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>select(+b.dataset.i,true)))}
function select(i,show=true){sel=(i+sections.length)%sections.length;const s=sections[sel];orb.textContent=s[1];orb.style.boxShadow=`0 0 28px ${s[3]}`;title.textContent=s[2];desc.textContent=s[4];chips.innerHTML=s[5].map(c=>`<span class="chip">${c}</span>`).join('');deck.innerHTML=s[6].map(c=>`<article class="card"><h3>${c[0]}</h3><p>${c[1]}</p></article>`).join('');count.textContent=`${sel+1} / ${sections.length}`;renderNav();if(show){panel.classList.add('show');intro.classList.add('hide')}}

document.getElementById('explore').addEventListener('click',()=>select(0,true));
document.getElementById('prev').addEventListener('click',()=>select(sel-1,true));
document.getElementById('next').addEventListener('click',()=>select(sel+1,true));
document.getElementById('brand').addEventListener('click',()=>{panel.classList.remove('show');intro.classList.remove('hide')});

document.querySelectorAll('.starr-orb').forEach(btn=>{btn.addEventListener('click',()=>{const target=Number(btn.dataset.target);btn.classList.add('is-opening');setTimeout(()=>btn.classList.remove('is-opening'),720);select(target,true);panel.classList.add('show');intro.classList.add('hide')})});

avatar.addEventListener('load',()=>{avatar.classList.add('loaded');status.textContent='3D Ready Mode'});
avatar.addEventListener('error',()=>{avatar.classList.add('failed');status.textContent='Model Error';modelError.classList.add('show')});
bgVideo.addEventListener('ended',()=>document.body.classList.add('bg-ended'));
bgVideo.addEventListener('error',()=>document.body.classList.add('bg-ended'));
bgVideo.play().catch(()=>{});
setTimeout(()=>{if(!avatar.classList.contains('loaded'))status.textContent='Still loading model'},6500);
renderNav();select(0,false);panel.classList.remove('show');